
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

discovery:
  ignore:
    - philips_hue
  
# BLINK CAMERAS
blink:
  username: !secret blink_user
  password: !secret blink_pass
  scan_interval: 300
  binary_sensors:
    monitored_conditions:
      - motion_enabled
      - motion_detected
  sensors:
    monitored_conditions:
      - battery
      - temperature
      - wifi_strength

# DUCK DNS
duckdns:
  domain: 4612barbados
  access_token: !secret duckdns_key
  
http:
  base_url: https://4612barbados.duckdns.org
#  ssl_certificate: /data/letsencrypt/live/4612barbados.duckdns.org/fullchain.pem
#  ssl_key: /data/letsencrypt/live/4612barbados.duckdns.org/privkey.pem
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem